### ISSUE TITLE
Add Ruby 2.7 support

### ISSUE THREAD

**Issue by balasankarc** [norman/babosa#51]
On Ruby 2.7, running the tests yield the following failure

```
$ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]

$ bundle exec rspec
................................F...............................................

Failures:

  1) Babosa::Identifier#to_ruby_method should raise an error when it would generate an impossible method name
     Failure/Error: expect {"1".to_identifier.to_ruby_method}.to raise_error(Babosa::Identifier::Error)
     
       expected Babosa::Identifier::Error, got #<FrozenError: can't modify frozen String: ""> with backtrace:
         # ./lib/babosa/identifier.rb:172:in `downcase!'
         # ./lib/babosa/identifier.rb:172:in `to_ruby_method!'
         # ./lib/babosa/identifier.rb:289:in `send_to_new_instance'
         # ./lib/babosa/identifier.rb:263:in `to_ruby_method'
         # ./spec/babosa_spec.rb:151:in `block (4 levels) in <top (required)>'
         # ./spec/babosa_spec.rb:151:in `block (3 levels) in <top (required)>'
     # ./spec/babosa_spec.rb:151:in `block (3 levels) in <top (required)>'

Finished in 0.06649 seconds (files took 0.20925 seconds to load)
80 examples, 1 failure

Failed examples:

rspec ./spec/babosa_spec.rb:149 # Babosa::Identifier#to_ruby_method should raise an error when it would generate an impossible method name
```

In Ruby 2.7, casting a `nil` object to String yields a frozen object, thanks to https://bugs.ruby-lang.org/issues/16150?next_issue_id=16184.

So, if `leader` and `trailer` in [`to_ruby_method`](https://github.com/norman/babosa/blob/master/lib/babosa/identifier.rb#L167) method are `nil`s, as is the case in the failing test, `to_s` yields frozen strings, on which we are attempting `downcase!`, which fails (obviously).

**Comment by balasankarc** [comment]
The following patch is a quick fix 

```diff
diff --git a/lib/babosa/identifier.rb b/lib/babosa/identifier.rb
index 8101aa3..486b678 100644
--- a/lib/babosa/identifier.rb
+++ b/lib/babosa/identifier.rb
@@ -166,8 +166,8 @@ module Babosa
     # Normalize a string so that it can safely be used as a Ruby method name.
     def to_ruby_method!(allow_bangs = true)
       leader, trailer = @wrapped_string.strip.scan(/\A(.+)(.)\z/).flatten
-      leader          = leader.to_s
-      trailer         = trailer.to_s
+      leader          = leader.to_s.dup
+      trailer         = trailer.to_s.dup
       if allow_bangs
         trailer.downcase!
         trailer.gsub!(/[^a-z0-9!=\\?]/, '')
```
